## code to prepare `ForestGeoProfile` dataset goes here

ForestGeoProfile <-
  list(
    TreeHeightUnitMan = "none",
    Family = "Family",
    TreeHeight = "none",
    Date = "ExactDate",
    Month = "none",
    Day = "none",
    POM = "none",
    HOM = "hom",
    PlotAreaUnitMan = "none",
    Xutm = "none",
    IdStem = "stemID",
    PlotMan = "ForestGEO",
    Species = "Species",
    ScientificNameSepMan = "",
    Yplot = "gy",
    Ysubplot = "none",
    CircUnitMan = "none",
    BD = "none",
    BDUnitMan = "none",
    BPOM = "none",
    BHOM = "none",
    BHOMUnitMan = "none",
    BCirc = "none",
    BCircUnitMan = "none",
    IdMeasure = "MeasureID",
    IdLevel = "IDLevel",
    TreeFieldNum = "tag",
    ScientificName = "Latin",
    DateFormatMan = "yyyy-mm-dd",
    IdCensus = "CensusID",
    PlotAreaMan = NULL,
    Year = "none",
    LifeStatus = "DFstatus",
    PlotArea = "none",
    CommercialSp = "none",
    SubPlotAreaUnitMan = "none",
    Yutm = "none",
    utmUnitMan = "none",
    YearMan = NA,
    Circ = "none",
    SubPlotAreaMan = "",
    SubPlotMan = "",
    Site = "none",
    Lon = "none",
    Plot = "none",
    IdTree = "treeID",
    LifeForm = "none",
    VernName = "none",
    SubPlotArea = "none",
    SiteMan = "",
    IsLiveMan = c("alive", "broken below"),
    Authority = "SpeciesID",
    Lat = "none",
    Genus = "Genus",
    SubPlot = "quadrat",
    DiameterUnitMan = "mm",
    Xplot = "gx",
    Xsubplot = "none",
    plotUnitMan = "m",
    subplotUnitMan = "none",
    Diameter = "dbh",
    HOMUnitMan = "m",
    Variety = "none",
    Voucher = "none",
    Tidy = structure(0L, class = c("integer",
                                   "shinyActionButtonValue")),
    ClearValueName = structure(0L, class = c("integer",
                                             "shinyActionButtonValue")),
    TickedMelt3 = FALSE,
    Variablecolumns1 = c("sp",
                         "gx", "gy"),
    ValueName4 = "Specis",
    TickedMelt1 = FALSE,
    TickedMelt4 = FALSE,
    Variablecolumns3 = c("DFstatus", "status"),
    ValueName3 = "stau",
    TickedMelt2 = FALSE,
    Variablecolumns2 = c("pom",
                         "hom"),
    ValueName2 = "om",
    Variablecolumns4 = c("Species",
                         "SpeciesID"),
    ValueName1 = ""
  )
usethis::use_data(ForestGeoProfile, overwrite = TRUE)

# also save for the app
saveRDS(ForestGeoProfile, "inst/app/data/ForestGeoProfile.rds")

## For ForestGeoProfile.Rmd  run next line of code and paste in the item section of R/ForestGeoProfile.R
x <- read.csv("inst/app/data/interactive_items.csv")


write.csv(
  paste0(
    "#'   \\item{",
    names(ForestGeoProfile),
    "}",  ifelse(is.na(x$Label[match(names(ForestGeoProfile), x$ItemID)]), "{Some value entered via interaction with the Shiny app", paste0("{Value or column name in data set @ForestGeoSubset (", ForestGeoProfile, ") corresponding to ",
                                                                                                                                          x$Label[match(names(ForestGeoProfile), x$ItemID)])),
    "}"),
  "clipboard",
  quote = F,
  row.names = F
)

