
library(shinytest)
#  viewTestDiff("inst/app/", "ForestPlotToForestGEO_test")
#  snapshotUpdate("inst/app/", "ForestPlotToForestGEO_test")


app <- ShinyDriver$new("../../")
app$snapshotInit("ForestPlotToForestGEO_test")

app$setInputs(nTable = 2)
app$uploadFile(file1 = "ForestPlots_test2_trees_small.csv")
app$uploadFile(file2 = "ForestPlots_test2_plots_small.csv")
app$setInputs(submitTables = "click")
app$setInputs(SkipStack = "click")
app$setInputs(leftTable = "Table1")
app$setInputs(rightTable = "Table2")
app$setInputs(selectLeft = "click")
app$setInputs(selectRight = "click")
app$setInputs(leftKey = "PlotID")
app$setInputs(rightKey = "Plot ID")
app$setInputs(Merge = "click")
app$setInputs(GoToTidy = "click")
app$setInputs(VariableName = "MeasureID")
app$setInputs(TickedMelt10 = TRUE)
app$setInputs(Variablecolumns10 = "POM")
app$setInputs(Variablecolumns10 = character(0))
app$setInputs(Variablecolumns10 = "POM")
app$setInputs(Variablecolumns10 = c("POM", "Extra POM"))
app$setInputs(TickedMelt13 = TRUE)
app$setInputs(ValueName13 = "DBH")
app$setInputs(Variablecolumns13 = c("D1", "CD1", "CD2"))
app$setInputs(Variablecolumns13 = c("D1", "Extra DPOMtMinus1", "CD1", "CD2"))
app$setInputs(Variablecolumns13 = c("D1", "CD1", "CD2"))
app$setInputs(Variablecolumns13 = c("D1", "Extra D", "CD1", "CD2"))
app$setInputs(Variablecolumns13 = c("D1", "Extra D", "CD2"))
app$setInputs(Variablecolumns13 = c("D1", "Extra D"))
app$setInputs(Tidy = "click")
app$setInputs(GoToHeaders = "click")
app$uploadFile(profile = "ForestPlots_test2_trees_small_Profile.rds")
app$setInputs(UseProfile = "click")
app$setInputs(UseProfile = "click")
app$setInputs(LaunchFormating = "click")
app$setInputs(GoToCorrect = "click")
app$setInputs(SkipCorrections = "click")
app$uploadFile(profileOutput = "ForestGEO_Profile.rds") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(UseProfileOuput = "click")
app$snapshot()
app$snapshotDownload("dbMetadata")
app$snapshotDownload("dbFile")
app$snapshotDownload("dbCode")
