#' ParacouProfile
#'
#' Generated by interacting with app or function RequiredFormat_interactive
#' @format A named list
#' \describe{
#'   \item{Authority}{Value or column name in data set @ParacouSubset (none) corresponding to  Taxonomic authority for the ID level}
#'   \item{BCirc}{Value or column name in data set @ParacouSubset (none) corresponding to Basal Circumference}
#'   \item{BCircUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your basal circumference unit?}
#'   \item{BD}{Value or column name in data set @ParacouSubset (none) corresponding to BD}
#'   \item{BDUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your BD unit ?}
#'   \item{Circ}{Value or column name in data set @ParacouSubset (Circ) corresponding to Circumference}
#'   \item{CircUnitMan}{Value or column name in data set @ParacouSubset (cm) corresponding to What is your circumference unit?}
#'   \item{ClearValueName}{Some value entered via interaction with the Shiny app}
#'   \item{CommercialSp}{Value or column name in data set @ParacouSubset (CommercialSp) corresponding to Commercial species indicator}
#'   \item{Date}{Value or column name in data set @ParacouSubset (CensusDate) corresponding to Date of measurement}
#'   \item{Month}{Value or column name in data set @ParacouSubset (none) corresponding to Month of measurement}
#'   \item{Day}{Value or column name in data set @ParacouSubset (none) corresponding to Day of measurement}
#'   \item{DateFormatMan}{Value or column name in data set @ParacouSubset (yyyy-mm-dd) corresponding to What is your date format?}
#'   \item{Diameter}{Value or column name in data set @ParacouSubset (none) corresponding to DBH}
#'   \item{DiameterUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your DBH unit ?}
#'   \item{Family}{Value or column name in data set @ParacouSubset (Family) corresponding to Family name}
#'   \item{Genus}{Value or column name in data set @ParacouSubset (Genus) corresponding to Genus name}
#'   \item{HOM}{Value or column name in data set @ParacouSubset (none) corresponding to HOM}
#'   \item{HOMUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your HOM unit?}
#'   \item{IdCensus}{Value or column name in data set @ParacouSubset (none) corresponding to Census ID}
#'   \item{IdLevel}{Value or column name in data set @ParacouSubset (none) corresponding to Deepest taxonomic level for which full identification is known}
#'   \item{IdMeasure}{Value or column name in data set @ParacouSubset (none) corresponding to Measure ID}
#'   \item{IdStem}{Value or column name in data set @ParacouSubset (none) corresponding to Stem ID}
#'   \item{IdTree}{Value or column name in data set @ParacouSubset (idTree) corresponding to Tree ID}
#'   \item{IsCommercialMan}{Value or column name in data set @ParacouSubset (TRUE) corresponding to Which of the following(s) indicate a commercial species?}
#'   \item{IsLive}{Some value entered via interaction with the Shiny app}
#'   \item{Lat}{Some value entered via interaction with the Shiny app}
#'   \item{LifeForm}{Value or column name in data set @ParacouSubset (none) corresponding to Life form}
#'   \item{LifeStatus}{Value or column name in data set @ParacouSubset (CodeAlive) corresponding to Life status}
#'   \item{Lon}{Some value entered via interaction with the Shiny app}
#'   \item{MinDBH}{Value or column name in data set @ParacouSubset (none) corresponding to Minimum DBH}
#'   \item{MinDBHMan}{Value or column name in data set @ParacouSubset (-999) corresponding to What is the minimum diameter of trees included in your inventory?}
#'   \item{MinDBHUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your unit for the column indicating the minimum DBH? If not provided, it will be calculated looking at your Diameter column}
#'   \item{Plot}{Value or column name in data set @ParacouSubset (Plot) corresponding to Plot name}
#'   \item{PlotArea}{Value or column name in data set @ParacouSubset (PlotArea) corresponding to Plot area}
#'   \item{PlotAreaMan}{Value or column name in data set @ParacouSubset (-999) corresponding to What is your plot area in hectare?}
#'   \item{PlotAreaUnitMan}{Value or column name in data set @ParacouSubset (ha) corresponding to What is the unit for plot area?}
#'   \item{PlotMan}{Value or column name in data set @ParacouSubset () corresponding to What is your plot name ?}
#'   \item{plotUnitMan}{Some value entered via interaction with the Shiny app}
#'   \item{POM}{Value or column name in data set @ParacouSubset (MeasCode) corresponding to POM}
#'   \item{ScientificName}{Value or column name in data set @ParacouSubset (none) corresponding to Scientific name}
#'   \item{ScientificNameSepMan}{Value or column name in data set @ParacouSubset () corresponding to Character separating Genus and Species in Scientific name}
#'   \item{Site}{Value or column name in data set @ParacouSubset (Forest) corresponding to Site name}
#'   \item{SiteMan}{Value or column name in data set @ParacouSubset () corresponding to What is your site name ?}
#'   \item{Species}{Value or column name in data set @ParacouSubset (Species) corresponding to Species name}
#'   \item{SubPlot}{Some value entered via interaction with the Shiny app}
#'   \item{SubPlotArea}{Some value entered via interaction with the Shiny app}
#'   \item{SubPlotAreaMan}{Some value entered via interaction with the Shiny app}
#'   \item{SubPlotAreaUnitMan}{Some value entered via interaction with the Shiny app}
#'   \item{SubPlotMan}{Some value entered via interaction with the Shiny app}
#'   \item{subplotUnitMan}{Some value entered via interaction with the Shiny app}
#'   \item{TickedMelt1}{Some value entered via interaction with the Shiny app}
#'   \item{TickedMelt2}{Some value entered via interaction with the Shiny app}
#'   \item{TickedMelt3}{Some value entered via interaction with the Shiny app}
#'   \item{Tidy}{Some value entered via interaction with the Shiny app}
#'   \item{TreeCodes}{Value or column name in data set @ParacouSubset (none) corresponding to Select all the columns that give information about your tree, and/or your methods of measurements}
#'   \item{TreeFieldNum}{Value or column name in data set @ParacouSubset (TreeFieldNum) corresponding to Tree tag}
#'   \item{TreeHeight}{Value or column name in data set @ParacouSubset (none) corresponding to Tree height}
#'   \item{TreeHeightUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your tree height unit?}
#'   \item{utmUnitMan}{Some value entered via interaction with the Shiny app}
#'   \item{ValueName1}{Some value entered via interaction with the Shiny app}
#'   \item{ValueName2}{Some value entered via interaction with the Shiny app}
#'   \item{ValueName3}{Some value entered via interaction with the Shiny app}
#'   \item{Variablecolumns1}{Some value entered via interaction with the Shiny app}
#'   \item{Variablecolumns2}{Some value entered via interaction with the Shiny app}
#'   \item{Variablecolumns3}{Some value entered via interaction with the Shiny app}
#'   \item{VernName}{Value or column name in data set @ParacouSubset (VernName) corresponding to Vernacular name}
#'   \item{Xplot}{Some value entered via interaction with the Shiny app}
#'   \item{Xsubplot}{Some value entered via interaction with the Shiny app}
#'   \item{Xutm}{Some value entered via interaction with the Shiny app}
#'   \item{Year}{Value or column name in data set @ParacouSubset (CensusYear) corresponding to Year of measurement}
#'   \item{YearMan}{Value or column name in data set @ParacouSubset (-999) corresponding to What is your year of measurement?}
#'   \item{Yfield}{Some value entered via interaction with the Shiny app}
#'   \item{Yplot}{Some value entered via interaction with the Shiny app}
#'   \item{Ysubplot}{Some value entered via interaction with the Shiny app}
#'   \item{Yutm}{Some value entered via interaction with the Shiny app}
#'   ...
#' }

#'
"ParacouProfile"
